#!/usr/bin/env bash
# a Bash script that install a nginx
# and configures a new Ubuntu machine
 
sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo service nginx restart
