#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

# Update package list and install Nginx
sudo apt update
sudo apt install -y nginx

# Create directory and index.html file (if they don't exist)
sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo bash -c 'echo "Hello World!" > /etc/nginx/html/index.html'

# Configure Nginx for redirection
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Restart Nginx to apply the configuration
sudo service nginx restart
