#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page.
# Contains the string "Ceci n'est pas une page"

# Update package list and install Nginx
sudo apt update
sudo apt install -y nginx

# Create directory and 404.html file (if they don't exist)
sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo bash -c 'echo "Hello World!" > /etc/nginx/html/index.html'
sudo touch /etc/nginx/html/404.html
sudo bash -c 'echo "Ceci n'\''est pas une page" > /etc/nginx/html/404.html'
sudo bash -c 'echo "" >> /etc/nginx/html/404.html'
# Configure Nginx for custom 404 page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF'

# Restart Nginx to apply the configuration
sudo service nginx restart
