#!/usr/bin/env bash
#script that add a user with restricted access and the ownership over the nginx process

pkill apache2
chown -R nginx:nginx /etc/nginx
chmod 644 /etc/nginx/nginx.conf
chmod 755 /etc/nginx
sed -i 's/#user/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx start
